### ISSUE TITLE
问下复现的硬件清单

### ISSUE THREAD

**Issue by YYGe01** [TommyZihao/openvino_tonypi#1]
子豪兄您好：
      请问下，要复现是不是只需要购买：幻尔科技TonyPi人形机器人（豪华版+树莓派5）+带GPU的笔记本就够用了，
      树莓派5的内存4G/8G怎么选呢，以及笔记本GPU的显存需要多大呢，谢谢！

**Comment by Twinhead880** [comment]
Traceback (most recent call last):
  File "D:\tools\python\pycharm\pycharm-professional-2024.1.win\plugins\python\helpers\pydev\pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\python\pycharm\pycharm-professional-2024.1.win\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\work\code\python\Qwen2.openvino\test_qwen2.5.py", line 8, in <module>
    pipe = ov_genai.LLMPipeline(r"D:\tools\AI\llm\Qwen\Qwen2.5-7B-Instruct-int4-ov", device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src/inference/src/cpp/core.cpp:124:
Exception from src/inference/src/dev/plugin.cpp:58:
Exception from src/frontends/ir/src/ir_deserializer.cpp:932:
Cannot create SpecialTokensSplit layer SpecialTokensSplit_160376 id:15 from unsupported opset: extension

请教一下，为什么我这里无法运行你已经量化好的模型？问题出在哪里？
